### ISSUE TITLE
디스코드 봇 서비스 제공

### ISSUE THREAD

**Issue by daryeou** [gillyongs/github.io#1]
지인의 소개로 이 프로젝트를 알게되었습니다.
러브라뗴 변환기 내용에 흥미가 있어서 디스코드 봇으로 제작하였으나,
라이센스 명시나 연락 수단을 찾지 못하여 남깁니다.

해당 봇을 비영리 목적으로 서비스하거나, 관련하여 대화를 나누고 싶은데 가능할까요?

시연 영상입니다 https://i.imgur.com/HWeq36q.gif

**Comment by gillyongs** [comment]
이제 봐서 답장드립니당
넵 원하는대로 쓰셔도 돼용


2023년 2월 23일 (목) 오전 8:56, K.Wonjo ***@***.***>님이 작성:

**Comment by daryeou** [comment]
@gillyongs 감사합니다.
